changelog:
  categories:
    - title: Desktop App
      labels:
        - electron
    - title: Web Application
      labels:
        - web
    - title: Companion Services
      labels:
        - microservices
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - '*'